Religieuze feestdagen
* Maria Hemelvaart
O.L.V. hemelvaart:  28 Augustus 2015
Maria-Tenhemelopneming of Onze-Lieve-Vrouw Hemelvaart is de katholieke feestdag waarop de opneming van Maria in de hemel "met lichaam en ziel" wordt herdacht en gevierd
Over het overlijden en vervolgens met lichaam en ziel opgenomen worden in de hemel van Maria zijn verschillende verhalen in omloop die uit de kerkelijke traditie afkomstig zijn. In de Bijbel wordt er niet over geschreven. Maria moet ergens tussen 36 en 50 n.Chr. zijn overleden ofwel in Jeruzalem ofwel in Ephese. Volgens een bepaalde traditie waren alle apostelen hierbij aanwezig, behalve Tomas. Toen deze aankwam was Maria's lichaam al begraven en om haar toch eer te bewijzen bezocht Tomas in zijn eentje haar graf. Tomas zag toen de tenhemelopneming van Maria. Daarbij kreeg hij van Maria haar gordel. De overige apostelen geloofden dit niet totdat hij hun de gordel toonde en het lege graf. Een opmerkelijke omkering van de situatie toen Tomas als enige apostel aanvankelijk niet geloofde in de verrezen Christus.
* Rosj Hasjana (Joods Nieuwjaar)
Datum: maandag 14 en dinsdag 15 september 2015
Iedere ochtend van deze bijzondere maand horen zij het geschal van de sjofar, de ramshoorn. Dan worden zij eraan herinnerd dat het een bijzondere tijd is en dat een heilige periode op het punt staat aan te breken.
* Offerfeest (Eid al-Adha):  4 oktober 2014
 Dit is 70 dagen na het einde van de Ramadan.
Het Offerfeest, Slachtfeest of het Grote Feest (Arabisch: عيد الأضحى, Id al-Adha) is het tweede Id-feest in de Islam. Het wordt gevierd ter nagedachtenis aan de profeet Ibrahim, die bereid was zijn zoon te offeren in opdracht van God.
Het Offerfeest is het grote feest terwijl het Suikerfeest het kleine feest wordt genoemd.
Op deze dag worden door moslims dieren die volgens dhabiha geslacht zijn gegeten. Het vlees wordt door hen gegeten en verdeeld onder armen, buren en familieleden. Doorgaans slacht men in België of Nederland een schaap of lam, waardoor het feest de bijnaam het offerfeest kreeg. Om een overschot aan vlees te voorkomen kunnen meerdere mensen samen een dier slachten.
* Allerheiligen:   8 November 2014
* Pasen:  12 April 2015
* Aswoensdag
* Pinksteren
* Kerstmis (TODO)
* Jom Kippoer: 4 oktober 2014
Jom Kip(p)oer of Grote Verzoendag (Hebreeuws: יום כיפור), voluit Jom ha-Kippoeriem ofwel Dag van de Vergevingen (meervoud), wordt als de belangrijkste en heiligste dag beschouwd in het jodendom. Het was de ene dag in het jaar dat de hogepriester de allerheiligste plaats in de tempel te Jeruzalem betrad om te pleiten voor Gods volk.
* O.H. Hemelvaart:  21 Mei 2015
Op Hemelvaartsdag (Latijn: Ascensio Domini) wordt binnen het christendom herdacht dat Jezus Christus is opgevaren naar God, zijn vader in de hemel, op de veertigste dag van Zijn opstanding. De viering is onderdeel van de paascyclus.
